### ISSUE TITLE
Add documentation for contributors

### ISSUE THREAD

**Issue by ryanwilsonperkin** [waveaccounting/vero-python#12]

**Comment by sktse** [comment]
@ryanwilsonperkin 
![ghosts](https://img.buzzfeed.com/buzzfeed-static/static/2019-08/1/18/asset/eda91369fe12/anigif_sub-buzz-1810-1564685166-1.gif)

**Comment by hockeybuggy** [comment]
![](https://memegenerator.net/img/instances/53880951/he-doesnt-even-go-here.jpg)
