### ISSUE TITLE
Do you really need this specific version of requests?

### ISSUE THREAD

**Issue by bochecha** [waveaccounting/vero-python#26]
I'm trying to use your Vero client in a project, and overall it looks great!

I just have one tiny issue, but it's turning into a blocker.

Your Vero client requires requests==2.7.0.

I have another dependency in my project which requires a much more recent version of requests.

Maybe you meant to require requests>=2.7.0 instead?

**Comment by mwarkentin** [comment]
@bochecha You're right, we're not really playing nicely as a library here.

@ryanwilsonperkin Any thoughts on this? I think we can probably switch from

```
requires = ['requests==2.7.0']
tests_require = ['mock==1.0.1']
```

to 

```
requires = ['requests']
tests_require = ['mock']
```

**Comment by ryanwilsonperkin** [comment]
@bochecha thanks for flagging this for us! ⭐️
`requests` is pretty good at backwards compatibility, and it looks like there haven't been any breaking changes to the functionality that we're using here in the latest releases. Given that, I feel comfortable taking @mwarkentin's suggestion and un-limiting the versions we require.

If there's demand for it, I'd consider dropping these external dependencies altogether and just using urllib. The tests could be run in python3 which has `mock` built right in.

**Comment by ryanwilsonperkin** [comment]
@bochecha try installing our new `2.0.1` version and let us know if that works for you 😄

**Comment by bochecha** [comment]
Thanks for fixing this so quickly!

(and sorry for not coming back sooner)

> If there's demand for it, I'd consider dropping these external dependencies altogether and just using urllib.

We already use requests for other things, so we're not going to be the ones asking this. 😉 

> The tests could be run in python3 which has mock built right in.

We use this module in a Python 2 application, so if you dropped the mock dependency and only ran the tests on Python 3, we would be worse for it.
